pipeline { 
"    agent any" 
"    stages {" 
"        stage('Clone Repository') {" 
"            steps { git 'https://github.com/Eeirq/ImTrying.git' }" 
"        }" 
"        stage('Build Docker Image') {" 
"            steps { sh 'docker build -t mydjangoapp .' }" 
"        }" 
"        stage('Run Container') {" 
"            steps { sh 'docker run -p 8000:8000 mydjangoapp' }" 
"        }" 
"        stage('Deploy') {" 
"            steps { echo 'Deployment stage: Add steps for pushing to a server or cloud provider' }" 
"        }" 
"    }" 
"}" 
